version: "3.0"

services:
  go-service:
    build: ./go-service
    ports:
      - "3000:3000"
  
  nodejs-service:
    build: ./nodejs-service
    ports:
      - "3001:3000"

  python-service:
    build: ./python-service
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go-service
      - nodejs-service
      - python-service